---
# Install and configure Nginx Web server (default choice)
- include: nginx.yml
  when: webserver == "nginx"

# Install and configure Apache Web Server (httpd if Red Hat)
- include: apache.yml
  when: webserver == "apache"
